export const techImgUrls = {
    'HTML': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/HTML.svg',
    'CSS': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/CSS.svg',
    'JavaScript': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/JavaScript.svg',
    'lit-html': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/Lit-Dark.svg',
    'Page.js': 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/code_javascript.png',
    'Axios': 'https://avatars.githubusercontent.com/u/32372333?v=4',
    'Angular': 'https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/angularjs/angularjs-original.svg',
    'TypeScript': 'https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/typescript/typescript-original.svg',
    'Firebase': 'https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/firebase/firebase-plain.svg',
    'Puppeteer': 'https://github.com/mirokrastanov/Software-Engineering-SoftUni/blob/main/miscellaneous/puppeteer-1.png?raw=true',
    'React': 'https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/react/react-original.svg',
    'Appwrite': 'https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/appwrite/appwrite-original.svg',
    'Swipper.js': 'https://camo.githubusercontent.com/c81e6d0dd98ec84b73ff99f6933d480643a2060092cd11cb725fb9fadf0b2723/68747470733a2f2f7377697065726a732e636f6d2f696d616765732f7377697065722d6c6f676f2e737667',
    'Node.js': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/NodeJS-Dark.svg',
    'Express.js': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/ExpressJS-Dark.svg',
    'MongoDB': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/MongoDB.svg',
    'Mongoose': 'https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/mongoose/mongoose-original.svg',
    'Tailwind': 'https://raw.githubusercontent.com/tandpfun/skill-icons/main/icons/TailwindCSS-Dark.svg',
};

export const appData = [
    {
        id: 1,
        appName: 'Rock Paper Scissors',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/rock-paper-scissors.jfif',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '📄✂️ A Web implementation of the popular "Rock - Paper - Scissors" game.',
        extDemoURL: null,
        intDemoURL: '/apps/rps',
        imgArr: [],
        docsURL: 'https://github.com/mirokrastanov/RockPaperScissors/blob/main/README.md',
        sourceCodeURL: 'https://github.com/mirokrastanov/RockPaperScissors/blob/main/rockPaperScissors.js',
    },
    {
        id: 2,
        appName: 'Guess The Number',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/numbers-card-poster.jpg',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '❓ A simple web-based JavaScript Number Guessing Game.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 3,
        appName: 'Dino Jumping',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/DinoJumping/main/images/dino-cover.png',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '🦖 Web-based JavaScript implementation of the popular Chrome Dinosaur Game.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 4,
        appName: 'Snake',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/snakeJS/main/src/previews/snake-4.png',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '🎮🐍🍎Web-based JavaScript implementation of the popular game - Snake.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 5,
        appName: 'Breakout/Arkanoid',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/breakoutJS/main/src/previews/br-5.png',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '🎮⚾🌠▶ Web-based JavaScript implementation of the popular game - Breakout / Arkanoid.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 6,
        appName: 'Scientific Calculator',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/sc-calc-1.png',
        appType: 'Web App',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '🖥️📈 Feature-rich, web-based, JavaScript implementation of a scientific calculator with Light and Dark modes, usable History and number Conversions between different Numeral Systems.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 7,
        appName: 'SoftUni Wizard',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/softuni-wizard-game/main/src/images/wizard-cover-royalty-free-pixabay.jpg',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '📱🪄🎮🕹️ Web-based side-scrolling game - SoftUni Wizard. Created with JavaScript.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 8,
        appName: 'Solitaire',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/solitaire/main/images/solitaire-image.webp',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '♠️♥️♣️♦️ Web-based JavaScript implementation of the popular game - Solitaire.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 9,
        appName: 'Tic Tac Toe',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/tictactoe-1.png',
        appType: 'Web Game',
        techArr: ['HTML', 'CSS', 'JavaScript'],
        appInfo: '✖️ ⭕ Web-based JavaScript implementation of the popular game Tic Tac Toe.',
        extDemoURL: null,
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 10,
        appName: 'Weather & Air Quality',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Responsive-Weather-Application/main/src/images/github-doc/w-sidebar.png',
        appType: 'Front End SPA',
        techArr: ['HTML', 'CSS', 'JavaScript', 'lit-html', 'Axios', 'Page.js'],
        appInfo: '☀️ 🌤️ 🌧️ 🌨️ 🌡️ Web application with modern responsive design showing information about the weather, air quality & more.',
        extDemoURL: 'https://weather-a2a51.web.app/',
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 11,
        appName: 'NBA Dashboard',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/nba-dashboard-project/1.png',
        appType: 'Full Stack Web App',
        techArr: ['Angular', 'TypeScript', 'Firebase', 'Puppeteer', 'CSS', 'HTML'],
        appInfo: '🏀📆💻▶️ A Fully Responsive Full Stack Web Application offering a modern dashboard with NBA stats, team rosters, standings, news, analysis, transactions, player stats and more.',
        extDemoURL: 'https://nba-1-480a7.web.app/',
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 12,
        appName: 'TV Kingdom',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/tv-kingdom-assets/preview.png',
        appType: 'Full Stack Web App',
        techArr: ['React', 'JavaScript', 'Firebase', 'Appwrite', 'Swipper.js', 'HTML', 'CSS'],
        appInfo: '🎬📺🏰🎉TV Kingdom, where the magic of television meets the future: a modern, fully responsive, full-stack web application that unlocks a kingdom of limitless TV show data at your fingertips!',
        extDemoURL: 'https://kingdom-71759.web.app/',
        intDemoURL: null,
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    },
    {
        id: 13,
        appName: 'Real-time Chat App',
        appPoster: 'https://raw.githubusercontent.com/mirokrastanov/Software-Engineering-SoftUni/main/miscellaneous/js-websocket-chat/2.png',
        appType: 'Full Stack Web App',
        techArr: ['React', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind', 'Mongoose', 'JavaScript', 'HTML', 'CSS'],
        appInfo: '💬📱💻Socket.io-powered chat app enabling real-time messaging across multiple chat rooms, with live event updates and user presence.',
        extDemoURL: 'https://js-websocket-chat.onrender.com/',
        intDemoURL: null,
        notes: ['DEMO: First loading takes about 30 seconds.', 'Further ones are instant. Free Hosting limitation.'],
        imgArr: [],
        docsURL: '',
        sourceCodeURL: '',
    }
];
